name: lab4
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_webview_plugin: ^0.4.0
  js: ^0.6.5
  webview_flutter: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - web/time_service.js
